<h3 class="display-3">About APP</h3><br>
<img src="<?=App::config('url')?>public/img/ERplast.jpg" class="img-fluid rounded" alt="...">




<hr>
<h5 class="display-5">Creator</h5>
<p class="card-text"><small class="text-muted">***</small></p>
<div class="row justify-content-md-center">
    <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Nemanja Đurić</h5>
                <p class="card-text">Edunova, PP26 - 2022/2023</p>
                <img src="<?=App::config('url')?>public/img/nem.jpg" class="figure-img img-fluid rounded" alt="..." style="max-height: 400px;"><br>
                <a href="https://github.com/nduric92" target="_blank"><button type="button" class="btn btn-outline-warning btn-lg">GitHub</button></a>
                <a href="https://www.linkedin.com/in/nemanja-%C4%91uri%C4%87-42a03799/" target="_blank"><button type="button" class="btn btn-outline-info btn-lg">LinkedIn</button></a>
            </div>
        </div>
    </div>
</div>